app_rpt:  Channel initialization for PTT
AllStarLink/app_rpt pull request #426
Opened 2024-11-16 13:03 UTC by KB4MDD

app_rpt is not waiting long enough in rpt_setup_channels for chan_simpleusb to initialize the usb device before asserting PTT on/off.

This change adds a 250ms delay before asserting PTT on and another 50ms delay before asserting PTT off.

I believe the intention of the original code was to insure that the PTT was toggled immediately after the channel driver was created by app_rpt.

Testing by the effected users is needed. This may close #421 and #424.

2024-11-16 14:42 UTC, InterLinked1 requested changes

2024-11-16 14:42 UTC, InterLinked1 commented on apps/app_rpt.c
> +		usleep(250000);
Do not use usleep when sleeping on a channel, use `ast_safe_sleep` instead.
Keep in mind the latter uses ms, not us like usleep.

2024-11-16 14:42 UTC, InterLinked1 commented on apps/app_rpt.c
> +		/* Wait for the driver to finish initialization */
Why is 250 ms enough to finish initialization? Is there a more direct way to wait for initialization to finish? How do we know that has happened?

2024-11-21 18:39 UTC, Allan-N commented
FYI : I removed the delays that @KB4MDD added and added a log message inside kickptt() when called with the PTT pipe not yet established.  Here's the output :
```
[2024-11-21 13:30:52.289] ERROR[301772]: chan_simpleusb.c:655 kickptt: Channel 491301: Write skipped: no pttkick[]
[2024-11-21 13:30:52.289] ERROR[301772]: chan_simpleusb.c:655 kickptt: Channel 491301: Write skipped: no pttkick[]
```
This confirms @KB4MDD's analysis that app_rpt's PTT toggling was likely happening before the hiddriver() thread had a chance to initialize the GPIO pins (and PTT pipe).

With the SimpleUSB and USBRadio GPIO changes I added to correctly initialize the GPIO pins neither @KB4MDD or I think the toggling code is needed (and will be removed with the next commit).

2024-12-04 23:46 UTC, merged