[ASL2 PATCH] Replace xpmr.c '#define XPMR_VOX_HANGTIME' with a new conf var
AllStarLink/app_rpt pull request #430
Opened 2024-12-05 21:33 UTC by Allan-N

The ASL2 change (from https://github.com/AllStarLink/ASL-Asterisk/pull/34) did not get merged into the ASL3 source base. This commit effectivly pulls in those changes.

From: David Gleason <david@allscan.info>

Replace xpmr.c '#define XPMR_VOX_HANGTIME' with a new 'voxhangtime' cfg parameter set in usbradio.conf. When using usbradio in carrierfrom=vox mode this is the value the vox hang timer pChan->rxVoxTimer is set to in xpmr.c each time RX audio is detected. Making it configurable allows the default value of 2000mS to be reduced to a shorter time thereby preventing 2 seconds of silence being added to all node user transmissions. A value of 500mS seems to be much more optimal, and in my testing resulted in no false RX CD drops even when not talking. (xpmr.c's vox mode detects even quiet background noise and thereby supports reliable COS detection for radios that do not have a hardware COS line output.)

Add the new voxhangtime parm to chan_usbradio.c chan_usbradio_pvt struct, store_config(), xpmr.c createPmrChannel(), xpmr.h t_pmr_chan struct, and to configs/rpt/usbradio.conf and configs/samples/usbradio.conf.sample.

2024-12-05 22:49 UTC, InterLinked1 requested changes

2024-12-05 22:49 UTC, InterLinked1 commented on channels/chan_usbradio.c
> +	if(o->rxcdtype == CD_XPMR_VOX) {
if (

2024-12-05 22:49 UTC, InterLinked1 commented on channels/xpmr/xpmr.c
> +			pChan->rxVoxTimer=pChan->voxHangTime;	/* VOX HangTime in mS */
ms

2024-12-06 01:36 UTC, Allan-N commented on channels/chan_usbradio.c
> +	if(o->rxcdtype == CD_XPMR_VOX) {
Fixed.

2024-12-06 01:36 UTC, Allan-N commented on channels/xpmr/xpmr.c
> +			pChan->rxVoxTimer=pChan->voxHangTime;	/* VOX HangTime in mS */
Fixed.

2024-12-06 02:44 UTC, InterLinked1 approved these changes

2024-12-10 16:50 UTC, KB4MDD commented on configs/samples/usbradio.conf.sample
> +voxhangtime = 2000          ; If carrierfrom=vox, mS to wait detecting RX audio before setting rxcarrierdetect=0
To match the other sample entries, this should start with a semi-colon.

2024-12-10 19:09 UTC, KB4MDD approved these changes

2024-12-16 23:27 UTC, merged